framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        excluded_patterns:
            - '**/vendor/**/graphiql.min.js'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
